# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The IncludeOS Blog
description: The IncludeOS Blog
baseurl: "" # the subpath of your site, e.g. /blog
permalink: :year/:month/:day/:title
url: "http://blog.includeos.org" # the base hostname & protocol for your site
twitter_username: IncludeOS
github_username:  includeos

# Build settings
markdown: kramdown

gems:
  - jekyll-redirect-from
